# Generated by Django 6.0.2 on 2026-06-30 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_perfilusuario_alter_produto_codigo_gdoor_and_more'),
        ('venda', '0003_venda_finalizada_alter_venda_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='core.empresa'),
        ),
    ]
