# Generated by Django 6.0.2 on 2026-06-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_gdoor',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
