# Generated by Django 6.0.2 on 2026-07-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_produto_empresa_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
