# Generated by Django 6.0.2 on 2026-07-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ultima_sincronizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='enviar_telegram',
            field=models.BooleanField(default=False),
        ),
    ]
